apiVersion: apps/v1
kind: Deployment
metadata:
  name: exchangerateapp-deployment
  labels:
    app: exchangerateapp-app
spec:
  strategy:
    type: RollingUpdate
  replicas: 2
  selector:
    matchLabels:
      app: exchangerateapp-app
  template:
    metadata:
      labels:
        app: exchangerateapp-app
    spec:
      containers:
        - name: exchangerateapp
          image: inkgrey/exchangerateapp
          ports:
            - containerPort: 7071
              name: app
            - containerPort: 9089
              name: actuator
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "local"
          livenessProbe:
            httpGet:
              port: 9089
              path: /health
            failureThreshold: 1
            periodSeconds: 10
          readinessProbe:
            httpGet:
              port: 7071
              path: /healthcheck
            failureThreshold: 1
            periodSeconds: 10
          startupProbe:
            httpGet:
              port: 7071
              path: /healthcheck
            failureThreshold: 30
            periodSeconds: 10