apiVersion: v1
kind: Service
metadata:
  name: exchangeservice
  labels:
    app: exchangerateapp-app
spec:
  type: NodePort
  ports:
    - port: 8071
      targetPort: 7071
      protocol: TCP
      name: http
      nodePort: 31234
  selector:
    app: exchangerateapp-app